### ISSUE TITLE
Feature Request: Check envato for valid active support

### ISSUE THREAD

**Issue by inetbiz** [firstred/modselfupdate#1]
It would be nice to sell outside of PS modules. Envato seems to have lower prices for store owners to buy PS modules and themes. If you use envato api, the consumer inputs their user name and private key along with their purchase code.

This allows the module / theme designer to earn revenue for support. No updates given unless they renew their support for the module / theme at envato. Similar to this: http://www.wpexplorer.com/envato-wordpress-toolkit-guide/

**Comment by firstred** [comment]
Would be nice for modules from Envato to include an updater, indeed. The GitHub lib can be replaced with e.g. https://packagist.org/packages/morningtrain/envato-api in that case.

But this framework is not for commercial modules. Therefore, I'm closing this issue.
